################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/stm32f4xx_ll_adc.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/stm32f4xx_ll_gpio.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/stm32f4xx_ll_rcc.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_adc.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_gpio.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_it.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_pwm.c \
C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_rcc.c 

C_DEPS += \
./Application/User/u_driver/Src/stm32f4xx_ll_adc.d \
./Application/User/u_driver/Src/stm32f4xx_ll_gpio.d \
./Application/User/u_driver/Src/stm32f4xx_ll_rcc.d \
./Application/User/u_driver/Src/u_adc.d \
./Application/User/u_driver/Src/u_gpio.d \
./Application/User/u_driver/Src/u_it.d \
./Application/User/u_driver/Src/u_pwm.d \
./Application/User/u_driver/Src/u_rcc.d 

OBJS += \
./Application/User/u_driver/Src/stm32f4xx_ll_adc.o \
./Application/User/u_driver/Src/stm32f4xx_ll_gpio.o \
./Application/User/u_driver/Src/stm32f4xx_ll_rcc.o \
./Application/User/u_driver/Src/u_adc.o \
./Application/User/u_driver/Src/u_gpio.o \
./Application/User/u_driver/Src/u_it.o \
./Application/User/u_driver/Src/u_pwm.o \
./Application/User/u_driver/Src/u_rcc.o 


# Each subdirectory must supply rules for building sources it contributes
Application/User/u_driver/Src/stm32f4xx_ll_adc.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/stm32f4xx_ll_adc.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/stm32f4xx_ll_gpio.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/stm32f4xx_ll_gpio.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/stm32f4xx_ll_rcc.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/stm32f4xx_ll_rcc.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/u_adc.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_adc.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/u_gpio.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_gpio.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/u_it.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_it.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/u_pwm.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_pwm.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/u_driver/Src/u_rcc.o: C:/Project/CaoThangFinalProject/Test/Core/u_driver/Src/u_rcc.c Application/User/u_driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32F469xx -c -I../../Core/Inc -I"C:/Project/CaoThangFinalProject/Test/Core/u_task/Inc" -I"C:/Project/CaoThangFinalProject/Test/Core/u_driver/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../TouchGFX/gui/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/images/include -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../TouchGFX/generated/fonts/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-u_driver-2f-Src

clean-Application-2f-User-2f-u_driver-2f-Src:
	-$(RM) ./Application/User/u_driver/Src/stm32f4xx_ll_adc.cyclo ./Application/User/u_driver/Src/stm32f4xx_ll_adc.d ./Application/User/u_driver/Src/stm32f4xx_ll_adc.o ./Application/User/u_driver/Src/stm32f4xx_ll_adc.su ./Application/User/u_driver/Src/stm32f4xx_ll_gpio.cyclo ./Application/User/u_driver/Src/stm32f4xx_ll_gpio.d ./Application/User/u_driver/Src/stm32f4xx_ll_gpio.o ./Application/User/u_driver/Src/stm32f4xx_ll_gpio.su ./Application/User/u_driver/Src/stm32f4xx_ll_rcc.cyclo ./Application/User/u_driver/Src/stm32f4xx_ll_rcc.d ./Application/User/u_driver/Src/stm32f4xx_ll_rcc.o ./Application/User/u_driver/Src/stm32f4xx_ll_rcc.su ./Application/User/u_driver/Src/u_adc.cyclo ./Application/User/u_driver/Src/u_adc.d ./Application/User/u_driver/Src/u_adc.o ./Application/User/u_driver/Src/u_adc.su ./Application/User/u_driver/Src/u_gpio.cyclo ./Application/User/u_driver/Src/u_gpio.d ./Application/User/u_driver/Src/u_gpio.o ./Application/User/u_driver/Src/u_gpio.su ./Application/User/u_driver/Src/u_it.cyclo ./Application/User/u_driver/Src/u_it.d ./Application/User/u_driver/Src/u_it.o ./Application/User/u_driver/Src/u_it.su ./Application/User/u_driver/Src/u_pwm.cyclo ./Application/User/u_driver/Src/u_pwm.d ./Application/User/u_driver/Src/u_pwm.o ./Application/User/u_driver/Src/u_pwm.su ./Application/User/u_driver/Src/u_rcc.cyclo ./Application/User/u_driver/Src/u_rcc.d ./Application/User/u_driver/Src/u_rcc.o ./Application/User/u_driver/Src/u_rcc.su

.PHONY: clean-Application-2f-User-2f-u_driver-2f-Src

